### ISSUE TITLE
模型数据

### ISSUE THREAD

**Issue by zhangsan075300** [luomingshuang/Orient-Language-Recognition_OLR#1]
您好可以用一下您的模型和数据吗？

**Comment by luomingshuang** [comment]
您好，
&nbsp; &nbsp; &nbsp; 这个是公司的一个项目，数据和模型都在公司，没办法提供。希望代码对你有用！
祝好！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luomingshuang/Orient-Language-Recognition_OLR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月19日(星期二) 晚上6:29
收件人:&nbsp;"luomingshuang/Orient-Language-Recognition_OLR"<Orient-Language-Recognition_OLR@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[luomingshuang/Orient-Language-Recognition_OLR] 模型数据 (#1)





 
您好可以用一下您的模型和数据吗？
